#!/bin/sh

case "$1" in
    start)
        echo "Loading scull module"
        modprobe scull

        echo "Loading faulty module"
        modprobe faulty
        # Create device node for faulty
        MAJOR=$(awk '$2=="faulty" {print $1}' /proc/devices)
        mknod /dev/faulty c $MAJOR 0
        chmod 666 /dev/faulty

        echo "Loading hello module"
        modprobe hello
        ;;
    stop)
        echo "Unloading hello module"
        rmmod hello

        echo "Unloading faulty module"
        rm -f /dev/faulty
        rmmod faulty

        echo "Unloading scull module"
        rmmod scull
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
